#ifndef ERRS_H
#define ERRS_H

#define ERR_OPENING_INPUT_FILE 1
#define ERR_READING_INPUT 2

#define ERR_INVALID_ARGUMENT 101

#define ERR_CELL_BUFFER_ALLOCATION_FAILED 201
#define ERR_BUFFER_INDEX_OUT_OF_BOUNDS 202

#endif
